title: FaceSearch
description: Searches for faces in a given image using the Google Reverse Image Search engine.
theme: jekyll-theme-cayman
github:
  zip_url: https://github.com/IAmSuyogJadhav/FaceSearch/archive/master.zip
  tar_url: https://github.com/IAmSuyogJadhav/FaceSearch/tarball/master
  clone_url: https://github.com/IAmSuyogJadhav/FaceSearch.git
  owner_url: https://github.com/IAmSuyogJadhav
show_downloads: true
